const typeOptions = [
  // bottom
  {
    type: "bottom",
    name: "Light Pants",
    season: ["Spring", "Summer"],
    tags: ["Work", "Everyday", "Beach", "Dinner", "Loungewear"],
    minTemp: 18,
    maxTemp: 30,
  },
  {
    type: "bottom",
    name: "Warm Pants",
    season: ["Autumn", "Winter"],
    tags: ["Work", "Everyday", "Beach", "Dinner"],
    minTemp: -5,
    maxTemp: 18,
  },
  {
    type: "bottom",
    name: "Maxi Skirt",
    season: ["Spring", "Summer"],
    tags: ["Everyday", "Beach", "Work", "Date Night"],
    minTemp: 18,
    maxTemp: 32,
  },
  {
    type: "bottom",
    name: "Shorts",
    season: ["Spring", "Summer"],
    tags: ["Everyday", "Beach", "Outdoor", "Sports"],
    minTemp: 22,
    maxTemp: 40,
  },
  {
    type: "bottom",
    name: "Mini Skirt",
    season: ["Spring", "Summer", "Autumn"],
    tags: ["Date Night", "Party", "Everyday"],
    minTemp: 18,
    maxTemp: 32,
  },
  {
    type: "bottom",
    name: "Midi Skirt",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    tags: ["Work", "Everyday", "Wedding"],
    minTemp: 12,
    maxTemp: 30,
  },

  // top
  {
    type: "top",
    name: "T-Shirt",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    tags: ["Everyday", "Gym", "Outdoor"],
    minTemp: 18,
    maxTemp: 35,
  },
  {
    type: "top",
    name: "Sports Top",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    tags: ["Gym", "Outdoor"],
    minTemp: 15,
    maxTemp: 35,
  },
  {
    type: "top",
    name: "Light Shirt",
    season: ["Spring", "Summer", "Autumn"],
    tags: ["Work", "Dinner", "Everyday"],
    minTemp: 16,
    maxTemp: 28,
  },
  {
    type: "top",
    name: "Warm Shirt",
    season: ["Autumn", "Winter"],
    tags: ["Work", "Dinner", "Everyday"],
    minTemp: 5,
    maxTemp: 18,
  },
  {
    type: "top",
    name: "Tank Top",
    season: ["Spring", "Summer"],
    tags: ["Everyday", "Gym", "Outdoor"],
    minTemp: 22,
    maxTemp: 40,
  },
  {
    type: "top",
    name: "Light Jumper",
    season: ["Spring", "Autumn"],
    tags: ["Everyday", "Work", "Outdoor", "Dinner"],
    minTemp: 10,
    maxTemp: 20,
  },
  {
    type: "top",
    name: "Warm Jumper",
    season: ["Autumn", "Winter"],
    tags: ["Everyday", "Work", "Outdoor", "Dinner"],
    minTemp: -5,
    maxTemp: 12,
  },
  {
    type: "top",
    name: "Fancy Top",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    tags: ["Party", "Date Night", "Wedding", "Dinner"],
    minTemp: 15,
    maxTemp: 28,
  },

  // outer
  {
    type: "outer",
    name: "Light Jacket",
    season: ["Spring", "Autumn"],
    tags: ["Everyday", "Work", "Outdoor", "Dinner"],
    minTemp: 10,
    maxTemp: 20,
  },
  {
    type: "outer",
    name: "Winter Coat",
    season: ["Autumn", "Winter"],
    tags: ["Everyday", "Work", "Outdoor", "Dinner", "Date Night"],
    minTemp: -15,
    maxTemp: 10,
  },

  // onepiece
  {
    type: "onepiece",
    name: "Formal Dress/Jumpsuit",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    tags: ["Party", "Date Night", "Wedding", "Dinner"],
    minTemp: 15,
    maxTemp: 30,
  },
  {
    type: "onepiece",
    name: "Party Dress/Jumpsuit",
    season: ["Spring", "Summer", "Autumn", "Winter"],
    tags: ["Party", "Date Night", "Wedding", "Dinner"],
    minTemp: 16,
    maxTemp: 30,
  },
  {
    type: "onepiece",
    name: "Summer Dress/Jumpsuit",
    season: ["Spring", "Summer"],
    tags: ["Everyday", "Beach", "Date Night"],
    minTemp: 22,
    maxTemp: 40,
  },
  {
    type: "onepiece",
    name: "Warm Dress/Jumpsuit",
    season: ["Autumn", "Winter"],
    tags: ["Everyday", "Work", "Date Night"],
    minTemp: 8,
    maxTemp: 18,
  },
];

export default typeOptions;